<?php


require_once "extensions/AccessControl/AccessControl.php";


# This file was automatically generated by the MediaWiki 1.30.0
# installer. If you make manual changes, please keep track in case you
# need to recreate them later.
#
# See includes/DefaultSettings.php for all configurable settings
# and their default values, but don't forget to make changes in _this_
# file, not there.
#
# Further documentation for configuration settings may be found at:
# https://www.mediawiki.org/wiki/Manual:Configuration_settings

# Protect against web entry
if ( !defined( 'MEDIAWIKI' ) ) {
	exit;
}


#Local셋팅에서 문제 없을시 
#$wgSessionInsecureSecrets = true;


## Uncomment this to disable output compression
# $wgDisableOutputCompression = true;

$wgSitename = "DMS팀 위키";
$wgMetaNamespace = "DMS팀_위키";

## The URL base path to the directory containing the wiki;
## defaults for all runtime URL paths are based off of this.
## For more information on customizing the URLs
## (like /w/index.php/Page_title to /wiki/Page_title) please see:
## https://www.mediawiki.org/wiki/Manual:Short_URL
$wgScriptPath = "/wiki";

## The protocol and server name to use in fully-qualified URLs
$wgServer = "http://10.77.129.113";

## The URL path to static resources (images, scripts, etc.)
$wgResourceBasePath = $wgScriptPath;

## The URL path to the logo.  Make sure you change this from the default,
## or else you'll overwrite your logo when you upgrade!
$wgLogo = "$wgResourceBasePath/resources/assets/nhnace.png";

## UPO means: this is also a user preference option

$wgEnableEmail = false;
$wgEnableUserEmail = true; # UPO

$wgEmergencyContact = "gusah1224@naver.com";
$wgPasswordSender = "gusah1224@naver.com";

$wgEnotifUserTalk = false; # UPO
$wgEnotifWatchlist = false; # UPO
$wgEmailAuthentication = true;

## Database settings
$wgDBtype = "mysql";
$wgDBserver = "localhost";
$wgDBname = "wiki";
$wgDBuser = "root";
$wgDBpassword = "afgsdh";

# MySQL specific settings
$wgDBprefix = "wiki";

# MySQL table options to use during installation or update
$wgDBTableOptions = "ENGINE=InnoDB, DEFAULT CHARSET=binary";

# Experimental charset support for MySQL 5.0.
$wgDBmysql5 = false;

## Shared memory settings
$wgMainCacheType = CACHE_NONE;
$wgMemCachedServers = [];

## To enable image uploads, make sure the 'images' directory
## is writable, then set this to true:
$wgEnableUploads = false;
#$wgUseImageMagick = true;
#$wgImageMagickConvertCommand = "/usr/bin/convert";

# InstantCommons allows wiki to use images from https://commons.wikimedia.org
$wgUseInstantCommons = false;

# Periodically send a pingback to https://www.mediawiki.org/ with basic data
# about this MediaWiki instance. The Wikimedia Foundation shares this data
# with MediaWiki developers to help guide future development efforts.
$wgPingback = true;

## If you use ImageMagick (or any other shell command) on a
## Linux server, this will need to be set to the name of an
## available UTF-8 locale
$wgShellLocale = "C.UTF-8";

## Set $wgCacheDirectory to a writable directory on the web server
## to make your wiki go slightly faster. The directory should not
## be publically accessible from the web.
#$wgCacheDirectory = "$IP/cache";

# Site language code, should be one of the list in ./languages/data/Names.php
$wgLanguageCode = "ko";

$wgSecretKey = "c37c9d09d862eccbdb4e7830867190a4609e1c7801c99cf48f9d827b3f3f9d28";

# Changing this will log out all existing sessions.
$wgAuthenticationTokenVersion = "1";

# Site upgrade key. Must be set to a string (default provided) to turn on the
# web installer while LocalSettings.php is in place
$wgUpgradeKey = "ddc83c97f6dc0670";

## For attaching licensing metadata to pages, and displaying an
## appropriate copyright notice / icon. GNU Free Documentation
## License and Creative Commons licenses are supported so far.
$wgRightsPage = ""; # Set to the title of a wiki page that describes your license/copyright
$wgRightsUrl = "";
$wgRightsText = "";
$wgRightsIcon = "";

# Path to the GNU diff3 utility. Used for conflict resolution.
$wgDiff3 = "";

## Default skin: you can change the default skin. Use the internal symbolic
## names, ie 'vector', 'monobook':
$wgDefaultSkin = "vector";

# Enabled skins.
# The following skins were automatically enabled:
wfLoadSkin( 'CologneBlue' );
wfLoadSkin( 'Modern' );
wfLoadSkin( 'MonoBook' );
wfLoadSkin( 'Vector' );

#================================================
# End of automatically generated settings.
# Add more configuration options below.



#Access Control Plugin
#@AccessControl.php도 수정해야함 !!

$wgAdminCanReadAll = true;			// sysop users can read all restricted pages
$wgAccessControlRedirect = false;

##R&D파트
#네임스페이스 작성 (그룹 명과 동일하게)
$wgExtraNamespaces[3000] = "R&D파트";
$wgExtraNamespaces[3001] = "R&D파트_TALK";


$wgNamespaceProtection[3000] = array( 'editR&D파트' ); // permission "editfoo" required to edit the foo namespace
$wgNamespacesWithSubpages[3001] = true;            // subpages enabled for the foo namespace
$wgGroupPermissions['sysop']['editR&D파트'] = true;     // permission "editfoo" granted to users in the "sysop" group 
$wgGroupPermissions['user']['editR&D파트'] = true;


##--------------------------------------------------
##태깅파트
#네임스페이스 작성 (그룹명과 동일하게 )
#배열 주소는 3000대 부터 2개씩 
$wgExtraNamespaces[3002] = "태깅파트";
$wgExtraNamespaces[3003] = "태깅파트_TALK";


$wgNamespaceProtection[3002] = array( 'edit태깅파트' ); //"태깅파트"" 라는 권한을 생성 
$wgNamespacesWithSubpages[3003] = true;            
$wgGroupPermissions['sysop']['edit태깅파트'] = true;     //system operation에 태깅파트라는 권한 추가 .
$wgGroupPermissions['user']['edit태깅파트'] = true; //모든유저에게 태깅파트 수정 허용 

#<accesscontrol>Administrators,IT:Department,Sales(ro)</accesscontrol>
#추가.하면 해당 페이지에 등록된 사람들, 그룹만 볼 수있음 .

?>